-- We can also perform all of this operations using the UI
ALTER WAREHOUSE COMPUTE_WH RESUME;
ALTER WAREHOUSE COMPUTE_WH SUSPEND;
ALTER WAREHOUSE COMPUTE_WH SET WAREHOUSE_SIZE = 'SMALL';
ALTER WAREHOUSE COMPUTE_WH SET WAREHOUSE_SIZE = SMALL; -- THIS ALSO WORK

DROP WAREHOUSE EXERCISE_WH;




